name: 下载

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: download
      run: |
          sudo apt-get update && sudo apt-get install -y tree p7zip-full aria2
          weget https://d-e03.winudf.com/b/XAPK/Y29tLmFjdGl2aXNpb24uY2FsbG9mZHV0eS5zaG9vdGVyXzE1NTU5X2JkZWFjYzhm?_fn=Q2FsbCBvZiBEdXR5OiBNb2JpbGUgU2Vhc29uIDZfMS4wLjQ1X0FQS1B1cmUueGFwaw&_p=Y29tLmFjdGl2aXNpb24uY2FsbG9mZHV0eS5zaG9vdGVy&download_id=1471307597591388&is_hot=true&k=2fa62985668b7e420f69b210670ee5f266811d40&uu=https%3A%2F%2Fd-26.winudf.com%2Fb%2FXAPK%2FY29tLmFjdGl2aXNpb24uY2FsbG9mZHV0eS5zaG9vdGVyXzE1NTU5X2JkZWFjYzhm%3Fk%3D2c385aa8bd5a2ae7319a93740062b03d66811d40
          
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: file
        path: | 
            *.apks
