name: 下载

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: download
      run: |
          sudo apt-get update && sudo apt-get install -y tree p7zip-full aria2
          aria2c https://d.apkpure.com/b/APK/com.ss.squarehome2?versionCode=30013&nc=arm64-v8a%2Carmeabi-v7a%2Cx86%2Cx86_64&sv=21
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: file
        path: | 
            *.apks
